name = "moody-worker"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[[routes]]
pattern = "m-api.changgepd.top"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "moody-d1-test"
database_id = "a9591a5a-1c83-4c27-ad19-70a3aa4f11fc"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "moody-music-asset"

[vars]
SUPABASE_URL = "https://litovetdmuzslxzctko.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpdG92ZXRkbXV6c2xpeHpjdGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5Mjg2NDMsImV4cCI6MjA5MDUwNDY0M30.FKpmTo6W3rKWNHSZST7WmfOo23jXQEoSJztAxQeN_vk"
